### ISSUE TITLE
web build support

### ISSUE THREAD

**Issue by dev-ro** [merigo-labs/example-apps#2]
please provide an example for wallet adapter for web build

**Comment by merigo-labs** [comment]
Hi Kyle, 

The wallet adapter example should work across all platforms, did you run into a particular issue on web? 

If you're seeing an error similar to "window.crypto.subtle is undefined" that's because you need to use HTTPS with localhost to enable the browser's crypto library. I can't find the steps I was using to do this atm but you should be able to find it online.

**Comment by dev-ro** [comment]
i didn't try to use https. will do, thank you!
